# Preload any images you plan to use (one per line)
preload = /home/maxpw/nix-config/users/maxpw/wallpapers/futuristic-journey-simon-stalenhag-wide.jpg

# Apply to all monitors (the empty prefix before the comma means "all")
wallpaper = ,/home/maxpw/nix-config/users/maxpw/wallpapers/futuristic-journey-simon-stalenhag-wide.jpg

# Optional
splash = false
ipc = on
