{
  description = "NixOS & Nix-Darwin configuration by @maximilianpw";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-26.05";
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixpkgs-unstable";

    vite-plus = {
      url = "github:ryoppippi/nix-vite-plus";
      inputs.nixpkgs.follows = "nixpkgs-unstable";
    };

    home-manager.url = "github:nix-community/home-manager/release-26.05";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    fleet = {
      url = "github:maximilianpw/fleet/a5de8eaa245aef373594a1d2a4e2d27127f00f5f";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.home-manager.follows = "home-manager";
    };

    # Own terminal log viewer; pinned to a release tag so every host gets the
    # same binary without depending on the Homebrew tap.
    loggle = {
      url = "github:maximilianpw/loggle/v0.2.0";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Own email client, built from source for Kim's homelab. Private repository,
    # fetched with the evaluating user's GitHub SSH key. It keeps its own
    # nixpkgs: it needs Bun >= 1.4, which nixos-26.05 does not ship.
    superlocal.url = "git+ssh://git@github.com/maximilianpw/superlocal";

    nix-darwin.url = "github:nix-darwin/nix-darwin/nix-darwin-26.05";
    nix-darwin.inputs.nixpkgs.follows = "nixpkgs";

    hyprland.url = "github:hyprwm/Hyprland";

    fenix = {
      url = "github:nix-community/fenix";
      inputs.nixpkgs.follows = "nixpkgs-unstable";
    };

    sops-nix.url = "github:Mic92/sops-nix";
    sops-nix.inputs.nixpkgs.follows = "nixpkgs";

    nixos-wsl.url = "github:nix-community/NixOS-WSL";
    nixos-wsl.inputs.nixpkgs.follows = "nixpkgs";

    nixos-hardware.url = "github:NixOS/nixos-hardware";
    nixos-hardware.inputs.nixpkgs.follows = "nixpkgs";

    llm-agents.url = "github:numtide/llm-agents.nix";

    disko.url = "github:nix-community/disko";
    disko.inputs.nixpkgs.follows = "nixpkgs";

    git-hooks.url = "github:cachix/git-hooks.nix";
    git-hooks.inputs.nixpkgs.follows = "nixpkgs";

    nix-index-database.url = "github:nix-community/nix-index-database";
    nix-index-database.inputs.nixpkgs.follows = "nixpkgs";

    stylix.url = "github:nix-community/stylix/release-26.05";
    stylix.inputs.nixpkgs.follows = "nixpkgs";

    # Neovim configuration framework (users/maxpw/neovim). Its package set
    # follows nixpkgs-unstable, matching the editor Home Manager installs today.
    nixvim = {
      url = "github:nix-community/nixvim";
      inputs.nixpkgs.follows = "nixpkgs-unstable";
    };

    # Manifest-based $HOME linker, imported only by hosts with `hjem = true` in
    # lib/hosts.nix: its nix-darwin module adds launch agents even with no users.
    hjem = {
      url = "github:feel-co/hjem";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs @ {
    self,
    fenix,
    git-hooks,
    nixpkgs,
    ...
  }: let
    inherit (nixpkgs) lib;
    hosts = import ./lib/inventory.nix {inherit lib;};

    # Overlay to pull select packages from nixpkgs-unstable and add custom packages
    overlays = [
      fenix.overlays.default
      inputs.vite-plus.overlays.default
      (_: prev: let
        llm = inputs.llm-agents.packages.${prev.stdenv.hostPlatform.system};
        resignBunBinary = package: binaryPath:
          if prev.stdenv.hostPlatform.isDarwin
          then
            package.overrideAttrs (old: {
              # Nix rewrites Bun's Mach-O dependencies during fixup, which
              # invalidates the embedded signature and makes macOS kill it.
              nativeBuildInputs =
                (old.nativeBuildInputs or [])
                ++ [prev.darwin.sigtool];
              postFixup =
                (old.postFixup or "")
                + ''
                  codesign --force --sign - "$out/${binaryPath}"
                '';
            })
          else package;
        # hunk's executable is wrapped at $out/bin/hunk; sign the actual
        # Mach-O payload instead of the shell wrapper generated by Nix.
        hunk = resignBunBinary llm.hunk "share/hunk/bin/hunk";
        pi = resignBunBinary llm.pi "libexec/pi/pi";
      in {
        inherit (llm) claude-code;
        inherit (llm) codex;
        inherit (llm) opencode;
        inherit (llm) grok;
        inherit (llm) herdr;
        inherit (llm) executor;
        amp-cli = llm.amp;
        inherit pi;
        inherit (llm) skills;
        hunkdiff = hunk;
        inherit (llm) agent-browser;
      })
      (final: prev: let
        unstable = inputs.nixpkgs-unstable.legacyPackages.${prev.stdenv.hostPlatform.system};
      in {
        # Expose the full unstable channel for consumers that need a single
        # unstable package without shadowing the stable one globally (which
        # would force mass rebuilds of everything depending on it).
        inherit unstable;
        # direnv 2.37.1 fish tests get killed during build on macOS (sandbox/OOM)
        direnv = prev.direnv.overrideAttrs (_: {doCheck = false;});
        # Home Assistant integrations move on a monthly cadence, so keep Core
        # and its declarative extensions on the same current package set.
        inherit
          (unstable)
          home-assistant
          home-assistant-custom-lovelace-modules
          jujutsu
          zig
          ;
        helium = final.callPackage ./packages/helium.nix {};
        tunarr = final.callPackage ./packages/tunarr.nix {};
        # Keep Jellyfin's server, web client, and patched FFmpeg together on the
        # locked unstable package set so upgrades move them as one unit.
        inherit (unstable) jellyfin jellyfin-web jellyfin-ffmpeg;
        t3code = final.callPackage ./packages/t3code.nix {};
        obsidian = final.callPackage ./packages/obsidian.nix {};
        cliproxyapi = final.callPackage ./packages/cliproxyapi.nix {};
        cua-driver = final.callPackage ./packages/cua-driver.nix {};
        nextcloud-calendar = final.callPackage ./packages/nextcloud-calendar.nix {};
        lazygit-nvim-edit = final.callPackage ./packages/lazygit-nvim-edit.nix {};
        herdr-shell = final.callPackage ./packages/herdr-shell.nix {};
      })
    ];

    mkSystem = import ./lib/mksystem.nix {
      inherit overlays nixpkgs inputs;
    };

    mkConfiguredSystem = name: host:
      mkSystem name {
        inherit (host) darwin linuxDesktop system user userDir wsl;
        hostRecord = host;
        hostInventory = hosts;
        extraModules = map (moduleName: inputs.nixos-hardware.nixosModules.${moduleName}) host.hardwareModules;
      };

    nixosHosts = lib.filterAttrs (_: host: !host.darwin) hosts;
    darwinHosts = lib.filterAttrs (_: host: host.darwin) hosts;
    mkPkgs = system:
      import nixpkgs {
        inherit system overlays;
        config.allowUnfree = true;
      };

    # Nixvim editor packages; language tooling comes from the same stable
    # package set Home Manager uses.
    nvim = system:
      import ./users/maxpw/neovim/packages.nix {
        inherit inputs system;
        toolPkgs = mkPkgs system;
      };

    desktopKim = mkConfiguredSystem "kim" (hosts.kim
      // {
        linuxDesktop = true;
      });

    mkPreCommitCheck = system:
      git-hooks.lib.${system}.run {
        src = ./.;
        hooks = {
          actionlint.enable = true;
          alejandra.enable = true;
          statix.enable = true;
          statix.settings.ignore = ["machines/hardware"];
          deadnix = {
            enable = true;
            excludes = ["machines/hardware/.*"];
            settings.exclude = ["machines/hardware"];
          };
        };
      };
  in {
    # Host outputs and fleet metadata derive from one typed, data-only source.
    lib.hosts = hosts;
    nixosConfigurations = lib.mapAttrs mkConfiguredSystem nixosHosts;
    darwinConfigurations = lib.mapAttrs mkConfiguredSystem darwinHosts;

    templates = {
      generic = {
        path = ./templates/generic;
        description = "Generic Nix devshell with direnv";
      };
      node = {
        path = ./templates/node;
        description = "Node.js project with pnpm";
      };
      rust = {
        path = ./templates/rust;
        description = "Rust project with fenix toolchain";
      };
    };

    # Locked reprovisioning tool. The layout itself remains intentionally
    # separate from live mounts and must only be run after a manual disk review.
    apps.x86_64-linux.disko = {
      type = "app";
      program = "${inputs.disko.packages.x86_64-linux.disko}/bin/disko";
    };

    # Eval-only checks catch typos, missing modules, and type errors without building.
    checks = import ./lib/checks.nix {
      inherit desktopKim hosts inputs lib mkPreCommitCheck nixpkgs nvim self;
    };

    # Custom packages exposed as flake outputs so `nix build .#<name>` and
    # `nix-update --flake <name>` can find them. The overlay still injects
    # these into `pkgs.*` for module consumption — this is additive.
    packages = let
      editorPackages = system: {
        inherit (nvim system) nvim nvim-vscode nvim-candidate nvim-vscode-candidate;
        inherit (mkPkgs system) lazygit-nvim-edit herdr-shell;
      };
    in {
      x86_64-linux = let
        pkgs = mkPkgs "x86_64-linux";
      in
        editorPackages "x86_64-linux"
        // {
          inherit (pkgs) helium obsidian skills cliproxyapi cua-driver nextcloud-calendar hunkdiff nix-update tunarr jellyfin jellyfin-web jellyfin-ffmpeg vite-plus t3code;
        };
      aarch64-darwin = let
        pkgs = mkPkgs "aarch64-darwin";
      in
        editorPackages "aarch64-darwin"
        // {
          inherit (pkgs) cua-driver skills nextcloud-calendar hunkdiff nix-update obsidian vite-plus t3code;
        };
    };

    formatter = nixpkgs.lib.genAttrs ["aarch64-linux" "x86_64-linux" "aarch64-darwin"] (
      system: nixpkgs.legacyPackages.${system}.alejandra
    );

    devShells = nixpkgs.lib.genAttrs ["aarch64-linux" "x86_64-linux" "aarch64-darwin"] (system: let
      pkgs = nixpkgs.legacyPackages.${system};
    in {
      default = pkgs.mkShell {
        buildInputs = with pkgs; [
          actionlint
          alejandra
          bashInteractive
          curl
          deadnix
          git
          gnumake
          gh
          jq
          nix
          nodejs
          python3
          rsync
          shellcheck
          statix
        ];
        shellHook = ''
          # Child terminals need completion/readline support, not stdenv's minimal Bash.
          export SHELL=${pkgs.bashInteractive}/bin/bash
          ${self.checks.${system}.pre-commit-check.shellHook or ""}
          echo "Welcome to the Nix dev shell for ${system}"
        '';
      };
    });
  };
}
