# Animations and Visual Effects
# ==============================

animations {
  enabled = yes
  workspace_wraparound = true
  bezier = ease, 0.20, 0.10, 0.10, 1.00
  animation = windows,    1, 3, ease, popin
  animation = windowsOut, 1, 4, ease, slide
  animation = border,     1, 6, ease
  animation = fade,       1, 6, ease
  animation = workspaces, 1, 3, ease, slide
}

decoration {
  rounding = 6
  active_opacity = 1.0
  inactive_opacity = 0.95

  dim_inactive = true
  dim_strength = 0.15

  blur {
    enabled = true
    size = 8
    passes = 3
    ignore_opacity = true
  }

  glow {
    enabled = true
    range = 10
    render_power = 3
    color = rgba(33ccffee)
    color_inactive = rgba(33ccff00)
  }
}
