{
  hostname,
  homeDirectory,
  lib,
  pkgs,
}: let
  inherit (lib) concatStringsSep escapeShellArg filterAttrs mapAttrs mapAttrs' mapAttrsToList nameValuePair optionalAttrs optionalString;

  inventory = import ./inventory.nix {inherit lib;};
  # Every managed host is a Fleet member. Keep the generated contract focused
  # on connection and agent capabilities; presentation and client secrets stay
  # in the typed inventory.
  hosts =
    mapAttrs (
      _: host:
        {
          inherit (host) aliases gui hostName longRunningAgents os port role tmuxCommand tmuxSession user;
          clientEnrolled = host.client != null;
        }
        // optionalAttrs (host.hostKey != null) {inherit (host) hostKey;}
        // optionalAttrs (host.plannotatorPort != null) {inherit (host) plannotatorPort;}
        // optionalAttrs (host.t3codePort != null) {inherit (host) t3codePort;}
    )
    inventory;

  boolText = value:
    if value
    then "true"
    else "false";

  contractRows =
    mapAttrsToList (
      name: host: let
        aliases = concatStringsSep ", " host.aliases;
      in ''
        ## ${name}

        - Aliases: ${
          if aliases == ""
          then "none"
          else aliases
        }
        - OS: ${host.os}
        - Role: ${host.role}
        - Remote user: ${host.user}
        - Target: ${host.hostName}
        - GUI/screenshot surface: ${boolText host.gui}
        - Long-running agents: ${boolText host.longRunningAgents}
        - Outbound Fleet identity enrolled: ${boolText host.clientEnrolled}
        ${optionalString (host ? plannotatorPort) "- Plannotator port: ${toString host.plannotatorPort} (forward on demand with `fleet forward`)\n"}
        ${optionalString (host ? t3codePort) "- T3 Code port: ${toString host.t3codePort}\n"}
      ''
    )
    hosts;

  contractText = ''
    # Revachol Fleet Agent Contract

    Generated from `lib/hosts.nix`; do not edit this file directly.

    ${concatStringsSep "\n" contractRows}
    ## Usage Rules

    - Use `fleet run <host> <command...>` for non-interactive remote checks.
    - Use `fleet ssh <host> [session] [--forward port]` inside a local Herdr pane for persistent remote tmux sessions and project ports.
    - Use `fleet shell <host>` for plain remote shells.
    - Use `fleet t3 <host>` for T3 Code port forwards when the host declares a T3 Code port.
    - Use `fleet forward list [local-port]` to inspect active SSH local forwards, then `fleet forward delete PID` to stop one.
    - Run long-running or unattended agent work only on hosts with `longRunningAgents = true`.
  '';

  remoteHosts = filterAttrs (name: _: name != hostname) hosts;
  localHost = hosts.${hostname} or null;
  localHostNames =
    if localHost == null
    then []
    else [hostname] ++ localHost.aliases;
  localHostPattern = concatStringsSep "|" localHostNames;

  hostPatterns = name: host: concatStringsSep " " ([name] ++ host.aliases);
  tmuxHostPatterns = name: host: concatStringsSep " " (map (alias: "tm-${alias}") ([name] ++ host.aliases));
  forwardHostPatterns = name: host: concatStringsSep " " (map (alias: "fleet-forward-${alias}") ([name] ++ host.aliases));
  caseHostPatterns = name: host: concatStringsSep "|" ([name] ++ host.aliases);

  baseSshOptions = {
    AddKeysToAgent = "yes";
    Compression = "yes";
    ControlMaster = "auto";
    ControlPath = "${homeDirectory}/.ssh/control-%C";
    ControlPersist = "10m";
    # Agent forwarding grants the remote host access to the local agent. Keep
    # the Fleet default off; a reviewed one-off SSH invocation can opt in.
    ForwardAgent = "no";
    ServerAliveCountMax = "3";
    ServerAliveInterval = "30";
    StrictHostKeyChecking = "accept-new";
  };

  # Hosts that declare a hostKey are pinned against the generated
  # fleet_known_hosts file; hosts without one stay on accept-new until
  # their key is captured (`ssh-keyscan -t ed25519 <host>`, cross-checked
  # against /etc/ssh/ssh_host_ed25519_key.pub on the host itself).
  pinnedHosts = filterAttrs (_: host: host ? hostKey) hosts;
  knownHostsFile = "${homeDirectory}/.ssh/fleet_known_hosts";

  localInventoryHost = inventory.${hostname} or null;
  localClient =
    if localInventoryHost == null
    then null
    else localInventoryHost.client;
  clientSshOptions = optionalAttrs (localClient != null) (
    {
      AddKeysToAgent = "no";
      IdentitiesOnly = "yes";
      IdentityFile = "${homeDirectory}/${localClient.identityFile}";
    }
    // optionalAttrs (localClient.identityAgent != null) {
      IdentityAgent = localClient.identityAgent;
    }
  );

  sshOptionsFor = host:
    baseSshOptions
    // (
      if host ? hostKey
      then {
        StrictHostKeyChecking = "yes";
        UserKnownHostsFile = "${knownHostsFile} ${homeDirectory}/.ssh/known_hosts";
      }
      else {}
    )
    // clientSshOptions;

  # Values use upstream OpenSSH directive names; the attr name becomes the
  # `Host <patterns>` line (programs.ssh.settings semantics).
  mkPlainBlock = name: host:
    nameValuePair (hostPatterns name host) ({
        HostName = host.hostName;
        User = host.user;
        Port = host.port;
      }
      // sshOptionsFor host);

  mkTmuxBlock = name: host:
    nameValuePair (tmuxHostPatterns name host) ({
        HostName = host.hostName;
        User = host.user;
        Port = host.port;
        RequestTTY = "yes";
        RemoteCommand = "${host.tmuxCommand} new-session -A -s ${host.tmuxSession}";
      }
      // sshOptionsFor host);

  mkForwardBlock = name: host:
    nameValuePair (forwardHostPatterns name host) ({
        HostName = host.hostName;
        User = host.user;
        Port = host.port;
      }
      // sshOptionsFor host);

  remoteTmuxRows =
    mapAttrsToList (
      name: host: ''
        ${caseHostPatterns name host}) printf '%s\n' ${escapeShellArg host.tmuxCommand} ;;
      ''
    )
    hosts;

  t3codePortRows =
    mapAttrsToList (
      name: host: ''
        ${caseHostPatterns name host}) printf '%s\n' ${escapeShellArg (toString host.t3codePort)} ;;
      ''
    )
    (filterAttrs (_: host: host ? t3codePort) hosts);

  hostRows =
    mapAttrsToList (
      name: host: let
        aliases = concatStringsSep "," host.aliases;
        client =
          if host.clientEnrolled
          then "yes"
          else "no";
        inherit (host) role;
      in ''
        printf '%-18s %-12s %-24s %-16s %-8s %s\n' ${escapeShellArg name} ${escapeShellArg host.user} ${escapeShellArg host.hostName} ${escapeShellArg role} ${escapeShellArg client} ${escapeShellArg aliases}
      ''
    )
    hosts;

  fleetTemplateMarkers = [
    "@LOCAL_HOST_CASE@"
    "@REMOTE_TMUX_ROWS@"
    "@T3CODE_PORT_ROWS@"
    "@CURRENT_HOST@"
    "@HOST_ROWS@"
  ];
  fleetScript = let
    rendered =
      lib.replaceStrings
      [
        "  # @LOCAL_HOST_CASE@\n  return 1"
        "    # @REMOTE_TMUX_ROWS@"
        "    # @T3CODE_PORT_ROWS@"
        "    # @CURRENT_HOST@"
        "    # @HOST_ROWS@"
      ]
      [
        (
          if localHostNames == []
          then "return 1"
          else ''
            case "$1" in
              ${localHostPattern}) return 0 ;;
              *) return 1 ;;
            esac
          ''
        )
        (concatStringsSep "\n        " remoteTmuxRows)
        (concatStringsSep "\n        " t3codePortRows)
        "printf 'Current machine: %s\\n\\n' ${escapeShellArg hostname}"
        (concatStringsSep "\n        " hostRows)
      ]
      (builtins.readFile ../scripts/fleet.sh);
  in
    assert lib.assertMsg
    (lib.all (marker: !lib.hasInfix marker rendered) fleetTemplateMarkers)
    "scripts/fleet.sh contains an unsubstituted template marker"; rendered;

  package = pkgs.writeShellApplication {
    name = "fleet";
    runtimeInputs = [
      pkgs.openssh
      pkgs.tmux
    ];
    text = fleetScript;
  };
in {
  inherit hosts package;

  aliases = {
    fl = "fleet list";
    fs = "fleet ssh";
    fsh = "fleet shell";
    fr = "fleet run";
  };

  files = {
    hostsJson = builtins.toJSON hosts;
    contract = contractText;
    knownHosts =
      concatStringsSep "\n"
      (mapAttrsToList (_: host: "${host.hostName} ${host.hostKey}") pinnedHosts)
      + "\n";
  };

  sshSettings =
    (mapAttrs' mkPlainBlock remoteHosts)
    // (mapAttrs' mkTmuxBlock remoteHosts)
    // (mapAttrs' mkForwardBlock remoteHosts);
}
