{
  hostname,
  homeDirectory,
  lib,
  pkgs,
  tunnels ? [],
}: let
  inherit (lib) concatStringsSep escapeShellArg filterAttrs listToAttrs mapAttrs mapAttrs' mapAttrsToList nameValuePair optionalAttrs optionalString unique;

  inventory = import ./inventory.nix {inherit lib;};
  # Every managed host is a Fleet member. Keep the generated contract focused
  # on connection and agent capabilities; presentation and client secrets stay
  # in the typed inventory.
  hosts =
    mapAttrs (
      _: host:
        {
          inherit (host) aliases gui hostName longRunningAgents os port role tmuxCommand tmuxSession user;
          clientEnrolled = host.client != null;
        }
        // optionalAttrs (host.hostKey != null) {inherit (host) hostKey;}
        // optionalAttrs (host.t3codePort != null) {inherit (host) t3codePort;}
    )
    inventory;

  boolText = value:
    if value
    then "true"
    else "false";

  contractRows =
    mapAttrsToList (
      name: host: let
        aliases = concatStringsSep ", " host.aliases;
      in ''
        ## ${name}

        - Aliases: ${
          if aliases == ""
          then "none"
          else aliases
        }
        - OS: ${host.os}
        - Role: ${host.role}
        - Remote user: ${host.user}
        - Target: ${host.hostName}
        - GUI/screenshot surface: ${boolText host.gui}
        - Long-running agents: ${boolText host.longRunningAgents}
        - Outbound Fleet identity enrolled: ${boolText host.clientEnrolled}
        ${optionalString (host ? t3codePort) "- T3 Code port: ${toString host.t3codePort}\n"}
      ''
    )
    hosts;

  contractText = ''
    # Revachol Fleet Agent Contract

    Generated from the Fleet inventory and Home Manager tunnel mappings; do not edit this file directly.

    ${concatStringsSep "\n" contractRows}
    ## Usage Rules

    - Use `fleet run <host> <command...>` for non-interactive remote checks.
    - Use `fleet ssh <host> [session] [--forward port]` inside a local Herdr pane for persistent remote tmux sessions and project ports.
    - Use `fleet shell <host>` for plain remote shells.
    - Use `fleet t3 <host>` for T3 Code port forwards when the host declares a T3 Code port.
    - Use `fleet forward list [local-port]` to inspect active SSH local forwards, then `fleet forward delete PID` to stop an unmanaged one. For managed ports, use `fleet tunnel pause PORT` instead: killing the SSH process only triggers a restart.
    - Use `fleet tunnel status`, `fleet tunnel pause PORT`, and `fleet tunnel resume PORT` for login-supervised localhost forwards on Darwin.
    - Use `fleet doctor HOST` to check SSH reachability, tunnel supervisor state, local port ownership, and whether the remote app is listening. A local listener is not end-to-end health.
    - Run long-running or unattended agent work only on hosts with `longRunningAgents = true`.
  '';

  remoteHosts = filterAttrs (name: _: name != hostname) hosts;
  localHost = hosts.${hostname} or null;
  localHostNames =
    if localHost == null
    then []
    else [hostname] ++ localHost.aliases;
  localHostPattern = concatStringsSep "|" localHostNames;

  hostPatterns = name: host: concatStringsSep " " ([name] ++ host.aliases);
  tmuxHostPatterns = name: host: concatStringsSep " " (map (alias: "tm-${alias}") ([name] ++ host.aliases));
  forwardHostPatterns = name: host: concatStringsSep " " (map (alias: "fleet-forward-${alias}") ([name] ++ host.aliases));
  caseHostPatterns = name: host: concatStringsSep "|" ([name] ++ host.aliases);

  baseSshOptions = {
    AddKeysToAgent = "yes";
    Compression = "yes";
    ControlMaster = "auto";
    ControlPath = "${homeDirectory}/.ssh/control-%C";
    ControlPersist = "10m";
    # Agent forwarding grants the remote host access to the local agent. Keep
    # the Fleet default off; a reviewed one-off SSH invocation can opt in.
    ForwardAgent = "no";
    ServerAliveCountMax = "3";
    ServerAliveInterval = "30";
    StrictHostKeyChecking = "accept-new";
  };

  # Hosts that declare a hostKey are pinned against the generated
  # fleet_known_hosts file; hosts without one stay on accept-new until
  # their key is captured (`ssh-keyscan -t ed25519 <host>`, cross-checked
  # against /etc/ssh/ssh_host_ed25519_key.pub on the host itself).
  pinnedHosts = filterAttrs (_: host: host ? hostKey) hosts;
  knownHostsFile = "${homeDirectory}/.ssh/fleet_known_hosts";

  localInventoryHost = inventory.${hostname} or null;
  localClient =
    if localInventoryHost == null
    then null
    else localInventoryHost.client;
  clientSshOptions = optionalAttrs (localClient != null) (
    {
      AddKeysToAgent = "no";
      IdentitiesOnly = "yes";
      IdentityFile = "${homeDirectory}/${localClient.identityFile}";
    }
    // optionalAttrs (localClient.identityAgent != null) {
      IdentityAgent = localClient.identityAgent;
    }
  );

  sshOptionsFor = host:
    baseSshOptions
    // (
      if host ? hostKey
      then {
        StrictHostKeyChecking = "yes";
        UserKnownHostsFile = "${knownHostsFile} ${homeDirectory}/.ssh/known_hosts";
      }
      else {}
    )
    // clientSshOptions;

  # Values use upstream OpenSSH directive names; the attr name becomes the
  # `Host <patterns>` line (programs.ssh.settings semantics).
  mkPlainBlock = name: host:
    nameValuePair (hostPatterns name host) ({
        HostName = host.hostName;
        User = host.user;
        Port = host.port;
      }
      // sshOptionsFor host);

  mkTmuxBlock = name: host:
    nameValuePair (tmuxHostPatterns name host) ({
        HostName = host.hostName;
        User = host.user;
        Port = host.port;
        RequestTTY = "yes";
        RemoteCommand = "${host.tmuxCommand} new-session -A -s ${host.tmuxSession}";
      }
      // sshOptionsFor host);

  mkForwardBlock = name: host:
    nameValuePair (forwardHostPatterns name host) ({
        HostName = host.hostName;
        User = host.user;
        Port = host.port;
      }
      // sshOptionsFor host);

  normalizeTunnel = t: {
    inherit (t) host localPort remotePort;
    remoteHost = t.remoteHost or "localhost";
  };
  managedTunnels = map normalizeTunnel tunnels;
  tunnelLocalPorts = map (t: t.localPort) managedTunnels;
  remoteTunnelNames = lib.flatten (mapAttrsToList (name: host: [name] ++ host.aliases) remoteHosts);
  tunnelLabelPrefix = "org.nix-community.home.";
  tunnelLabel = t: "${tunnelLabelPrefix}fleet-tunnel-${toString t.localPort}";
  tunnelAgentName = t: "fleet-tunnel-${toString t.localPort}";
  tunnelForwardSpec = t: "127.0.0.1:${toString t.localPort}:${t.remoteHost}:${toString t.remotePort}";
  tunnelRunner = pkgs.writeShellApplication {
    name = "fleet-tunnel-runner";
    runtimeInputs = [pkgs.openssh pkgs.coreutils pkgs.lsof];
    text = builtins.readFile ../scripts/fleet-tunnel-runner.sh;
  };
  tunnelSshArgs = t: [
    "${tunnelRunner}/bin/fleet-tunnel-runner"
    (toString t.localPort)
    "-o"
    "BatchMode=yes"
    "-o"
    "ConnectTimeout=10"
    "-o"
    "ExitOnForwardFailure=yes"
    "-o"
    "ForwardAgent=no"
    "-o"
    "ControlMaster=no"
    "-o"
    "ControlPath=none"
    "-o"
    "ServerAliveInterval=30"
    "-o"
    "ServerAliveCountMax=3"
    "-N"
    "-L"
    (tunnelForwardSpec t)
    "fleet-forward-${t.host}"
  ];
  mkTunnelAgent = t: {
    enable = true;
    config = {
      Label = tunnelLabel t;
      ProgramArguments = tunnelSshArgs t;
      RunAtLoad = true;
      KeepAlive = true;
      ThrottleInterval = 30;
      ProcessType = "Background";
    };
  };
  launchdAgents = listToAttrs (map (t: nameValuePair (tunnelAgentName t) (mkTunnelAgent t)) managedTunnels);
  tunnelMappingRows = concatStringsSep "\n" (map (t: "${toString t.localPort}|${t.host}|${toString t.remotePort}|${t.remoteHost}|${tunnelLabel t}") managedTunnels);
  tunnelSupervisor =
    if localInventoryHost != null && localInventoryHost.darwin
    then "launchd"
    else "none";
  tunnelContractRows = concatStringsSep "" (map (
      t: "- Managed tunnel: local ${toString t.localPort} -> ${t.host} ${t.remoteHost}:${toString t.remotePort}\n"
    )
    managedTunnels);

  canonicalHostRows =
    mapAttrsToList (name: host: ''
      ${caseHostPatterns name host}) printf '%s\n' ${escapeShellArg name} ;;
    '')
    hosts;

  remoteTmuxRows =
    mapAttrsToList (
      name: host: ''
        ${caseHostPatterns name host}) printf '%s\n' ${escapeShellArg host.tmuxCommand} ;;
      ''
    )
    hosts;

  t3codePortRows =
    mapAttrsToList (
      name: host: ''
        ${caseHostPatterns name host}) printf '%s\n' ${escapeShellArg (toString host.t3codePort)} ;;
      ''
    )
    (filterAttrs (_: host: host ? t3codePort) hosts);

  hostRows =
    mapAttrsToList (
      name: host: let
        aliases = concatStringsSep "," host.aliases;
        client =
          if host.clientEnrolled
          then "yes"
          else "no";
        inherit (host) role;
      in ''
        printf '%-18s %-12s %-24s %-16s %-8s %s\n' ${escapeShellArg name} ${escapeShellArg host.user} ${escapeShellArg host.hostName} ${escapeShellArg role} ${escapeShellArg client} ${escapeShellArg aliases}
      ''
    )
    hosts;

  fleetTemplateMarkers = [
    "@LOCAL_HOST_CASE@"
    "@REMOTE_TMUX_ROWS@"
    "@T3CODE_PORT_ROWS@"
    "@CURRENT_HOST@"
    "@HOST_ROWS@"
    "@TUNNEL_SUPERVISOR@"
    "@TUNNEL_MAPPING_ROWS@"
    "@TUNNEL_HELPERS@"
    "@CANONICAL_HOST_ROWS@"
  ];
  fleetScript = let
    rendered =
      lib.replaceStrings
      [
        "  # @LOCAL_HOST_CASE@\n  return 1"
        "    # @REMOTE_TMUX_ROWS@"
        "    # @T3CODE_PORT_ROWS@"
        "    # @CURRENT_HOST@"
        "    # @HOST_ROWS@"
        "  # @TUNNEL_SUPERVISOR@\n  printf '%s\\n' none"
        "# @TUNNEL_MAPPING_ROWS@"
        "# @TUNNEL_HELPERS@"
        "    # @CANONICAL_HOST_ROWS@"
      ]
      [
        (
          if localHostNames == []
          then "return 1"
          else ''
            case "$1" in
              ${localHostPattern}) return 0 ;;
              *) return 1 ;;
            esac
          ''
        )
        (concatStringsSep "\n        " remoteTmuxRows)
        (concatStringsSep "\n        " t3codePortRows)
        "printf 'Current machine: %s\\n\\n' ${escapeShellArg hostname}"
        (concatStringsSep "\n        " hostRows)
        "printf '%s\n' ${escapeShellArg tunnelSupervisor}"
        tunnelMappingRows
        (lib.removeSuffix "\n" (builtins.readFile ../scripts/fleet-tunnels.sh))
        (concatStringsSep "\n" canonicalHostRows)
      ]
      (builtins.readFile ../scripts/fleet.sh);
  in
    assert lib.assertMsg
    (lib.all (marker: !lib.hasInfix marker rendered) fleetTemplateMarkers)
    "scripts/fleet.sh contains an unsubstituted template marker"; rendered;

  package = pkgs.writeShellApplication {
    name = "fleet";
    runtimeInputs = [
      pkgs.openssh
      pkgs.tmux
      pkgs.bash
      pkgs.coreutils
      pkgs.gnugrep
      pkgs.lsof
    ];
    text = fleetScript;
  };
in
  assert lib.assertMsg (lib.length tunnelLocalPorts == lib.length (unique tunnelLocalPorts))
  "Fleet managed tunnels must use unique local ports";
  assert lib.assertMsg (lib.all (t: lib.elem t.host remoteTunnelNames) managedTunnels)
  "Fleet managed tunnel host must be a remote Fleet host or alias"; {
    inherit hosts launchdAgents managedTunnels package tunnelRunner;

    aliases = {
      fl = "fleet list";
      fs = "fleet ssh";
      fsh = "fleet shell";
      fr = "fleet run";
    };

    files = {
      hostsJson = builtins.toJSON hosts;
      contract =
        contractText
        + optionalString (managedTunnels != []) ''
          ## Managed localhost tunnels

          ${tunnelContractRows}
        '';
      knownHosts =
        concatStringsSep "\n"
        (mapAttrsToList (_: host: "${host.hostName} ${host.hostKey}") pinnedHosts)
        + "\n";
    };

    sshSettings =
      (mapAttrs' mkPlainBlock remoteHosts)
      // (mapAttrs' mkTmuxBlock remoteHosts)
      // (mapAttrs' mkForwardBlock remoteHosts);
  }
