#!/usr/bin/env bash

: "${T3CODE_SYSTEM_USER:?T3CODE_SYSTEM_USER must be set}"
: "${T3CODE_CASK_TOKEN:?T3CODE_CASK_TOKEN must be set}"
: "${T3CODE_RELEASE_VERSION:?T3CODE_RELEASE_VERSION must be set}"
: "${T3CODE_TAP_NAME:?T3CODE_TAP_NAME must be set}"

if [ -x /opt/homebrew/bin/brew ]; then
  run_t3code_brew() {
    sudo \
      --user="$T3CODE_SYSTEM_USER" \
      --set-home \
      -- /opt/homebrew/bin/brew "$@"
  }

  # Migrate from official stable/nightly casks without zapping shared
  # T3 Code state.
  for old_cask in t3-code t3-code@nightly; do
    if run_t3code_brew list --cask "$old_cask" >/dev/null 2>&1; then
      run_t3code_brew unpin --cask "$old_cask" >/dev/null 2>&1 || true
      run_t3code_brew uninstall --cask "$old_cask"
    fi
  done

  installed_t3code="$(
    run_t3code_brew list --cask --versions "$T3CODE_CASK_TOKEN" \
      2>/dev/null || true
  )"
  installed_t3code_version="${installed_t3code#* }"
  installed_t3code_app_version="$(
    /usr/libexec/PlistBuddy \
      -c "Print :CFBundleShortVersionString" \
      "/Applications/T3 Code (Nightly).app/Contents/Info.plist" \
      2>/dev/null || true
  )"

  if [ "$installed_t3code_version" != "$T3CODE_RELEASE_VERSION" ] ||
    [ "$installed_t3code_app_version" != "$T3CODE_RELEASE_VERSION" ]; then
    if [ -n "$installed_t3code" ]; then
      run_t3code_brew unpin --cask "$T3CODE_CASK_TOKEN" \
        >/dev/null 2>&1 || true
      run_t3code_brew uninstall --cask "$T3CODE_CASK_TOKEN"
    fi

    # Force Homebrew Bundle to clone the tap generated by this revision.
    run_t3code_brew untap --force "$T3CODE_TAP_NAME" \
      >/dev/null 2>&1 || true
  fi
fi
