#!/usr/bin/env bash

: "${T3CODE_SYSTEM_USER:?T3CODE_SYSTEM_USER must be set}"
: "${T3CODE_CASK_TOKEN:?T3CODE_CASK_TOKEN must be set}"
: "${T3CODE_RELEASE_VERSION:?T3CODE_RELEASE_VERSION must be set}"
: "${T3CODE_TAP_NAME:?T3CODE_TAP_NAME must be set}"
: "${T3CODE_TAP_URL:?T3CODE_TAP_URL must be set}"
: "${T3CODE_BREW_BIN:=/opt/homebrew/bin/brew}"
: "${T3CODE_PLISTBUDDY_BIN:=/usr/libexec/PlistBuddy}"

if [ -x "$T3CODE_BREW_BIN" ]; then
  run_t3code_brew() {
    sudo \
      --user="$T3CODE_SYSTEM_USER" \
      --set-home \
      -- "$T3CODE_BREW_BIN" "$@"
  }

  # Trust the installed tap before querying its cask. Bundle can later trust
  # a different Nix-store URL without replacing an already-installed tap.
  if run_t3code_brew tap | /usr/bin/grep -Fxq "$T3CODE_TAP_NAME"; then
    run_t3code_brew trust --tap "$T3CODE_TAP_NAME" >/dev/null
  fi

  # Migrate from official stable/nightly casks without zapping shared
  # T3 Code state.
  for old_cask in t3-code t3-code@nightly; do
    if run_t3code_brew list --cask "$old_cask" >/dev/null 2>&1; then
      run_t3code_brew unpin --cask "$old_cask" >/dev/null 2>&1 || true
      run_t3code_brew uninstall --cask "$old_cask"
    fi
  done

  installed_t3code="$(
    run_t3code_brew list --cask --versions "$T3CODE_CASK_TOKEN" \
      2>/dev/null || true
  )"
  installed_t3code_version="${installed_t3code#* }"
  installed_t3code_app_version="$(
    "$T3CODE_PLISTBUDDY_BIN" \
      -c "Print :CFBundleShortVersionString" \
      "/Applications/T3 Code (Nightly).app/Contents/Info.plist" \
      2>/dev/null || true
  )"

  if [ "$installed_t3code_version" != "$T3CODE_RELEASE_VERSION" ] ||
    [ "$installed_t3code_app_version" != "$T3CODE_RELEASE_VERSION" ]; then
    if [ -n "$installed_t3code" ]; then
      run_t3code_brew unpin --cask "$T3CODE_CASK_TOKEN" \
        >/dev/null 2>&1 || true
      run_t3code_brew uninstall --cask "$T3CODE_CASK_TOKEN"
    fi

    # Force Homebrew Bundle to clone the tap generated by this revision.
    run_t3code_brew untap --force "$T3CODE_TAP_NAME" \
      >/dev/null 2>&1 || true
  elif run_t3code_brew tap | /usr/bin/grep -Fxq "$T3CODE_TAP_NAME"; then
    # Re-clone when the generated Brewfile points at a new store path.
    # Otherwise Bundle's cleanup sees the old tap URL as untrusted.
    installed_tap_repo="$(run_t3code_brew --repo "$T3CODE_TAP_NAME")"
    installed_tap_url="$(sudo --user="$T3CODE_SYSTEM_USER" --set-home -- /usr/bin/git -C "$installed_tap_repo" remote get-url origin)"
    if [ "$installed_tap_url" != "$T3CODE_TAP_URL" ]; then
      run_t3code_brew untap --force "$T3CODE_TAP_NAME"
    fi
  fi
fi
