# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [];

  boot.initrd.availableKernelModules = ["uhci_hcd" "ahci" "xhci_pci" "nvme" "usbhid" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

fileSystems."/" = {
  device = "/dev/disk/by-uuid/28ed4a68-80f3-413e-9002-b7740b77ff8f";
  fsType = "ext4";
};
fileSystems."/boot" = {
  device = "/dev/disk/by-uuid/3068-3A88";
  fsType = "vfat";
};

  swapDevices = [];
}
