name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flake-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flake-checker-action@main

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [main-pc, wsl]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: cachix/cachix-action@v15
        with:
          name: maximilianpw
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel --no-link
